spring.application.name=InternshipDemands

spring.datasource.url=jdbc:mysql://localhost:3306/Internify?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8088
server.servlet.context-path=/internshipDemands

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youssefazzouz2@gmail.com
spring.mail.password=mazn amdi uhiq pxux
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false
